# Generated by Django 3.2.7 on 2021-09-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=30)),
                ('task_content', models.TextField(max_length=100)),
                ('task_added_date', models.DateField(blank=True)),
                ('task_due_date', models.DateField(blank=True)),
                ('task_due_time', models.TimeField(blank=True)),
                ('task_category', models.CharField(choices=[('None', 'None'), ('Personal', 'Personal'), ('Shopping', 'Shopping'), ('Wishlist', 'Wishlist'), ('Work', 'Work')], default='None', max_length=15)),
                ('task_repeat', models.CharField(choices=[('No_repeat', 'No Repeat'), ('Once_a_day', 'Once a Day'), ('Once_a_week', 'Once a Week'), ('Once_a_month', 'Once a Month'), ('Once_a_year', 'Once a Year')], default='No Repeat', max_length=15)),
                ('task_status', models.CharField(choices=[('Not_completed', 'Not Completed'), ('In_progress', 'In Progress'), ('Completed', 'Completed')], default='Not Completed', max_length=15)),
            ],
        ),
    ]
